routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


/* Route for Clients functionality */
Route::resource('client','ClientController')->except([
    'show'
]);

/* Route for Transaction functionality */
Route::resource('transaction','TransactionController')->except([
    'show'
]);

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\Transaction;
use Carbon\Carbon;
use Illuminate\Http\Request;
use DataTables;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if ($request->ajax()) {
            $transactions = \App\Transaction::leftJoin('clients', 'transactions.client_id', '=', 'clients.id')
                ->select(
                    'transactions.*',
                    \Illuminate\Support\Facades\DB::raw("CONCAT(clients.first_name,' ',clients.last_name) as client_name")
                );
            return DataTables::of($transactions)
                ->editColumn('client_name', function ($query) {
                    return $query->client_name;
                })
                ->editColumn('transaction_date', function ($query) {
                    return Carbon::parse($query->transaction_date)->format('Y-m-d');
                })
                ->addColumn('action', function ($query) {
                    $btn = '<a href="' . route('transaction.edit', $query->id) . '" class="btn dt-custom-button"><i class="fa fa-pencil fa-lg"></i> </a>
                            <a href="javascript:void(0)" onclick="deleteTransaction(' . $query->id . ')" class="btn dt-custom-button"><i class="fa fa-trash fa-lg"></i> </a>';
                    return $btn;
                })
                ->rawColumns(['action'])
                ->addIndexColumn()
                ->make(true);
        }

        return view('transaction.index');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clients = Client::get();
        return view('transaction.create', ['clients' => $clients]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'client_id' => 'required|not_in:0',
            'amount' => 'required',
            'transaction_date' => 'required'
        ]);

        Transaction::create([
            'client_id' => $request->client_id,
            'amount' => $request->amount,
            'transaction_date' => $request->transaction_date,
        ]);

        return redirect(route('transaction.index'))->with('success', 'Transaction Added Successfully.');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Transaction $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {
        $clients = Client::get();
        return view('transaction.edit', ['transaction' => $transaction, 'clients' => $clients]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Transaction $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction)
    {

        $this->validate($request, [
            'client_id' => 'required|not_in:0',
            'amount' => 'required',
            'transaction_date' => 'required'
        ]);

        $transaction->client_id = $request->client_id;
        $transaction->amount = $request->amount;
        $transaction->transaction_date = $request->transaction_date;
        $transaction->save();

        return redirect(route('transaction.index'))->with('success', 'Transaction Updated Successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Transaction $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        // delete transaction from database
        $transaction->delete();

        return response()->json([
            'success' => true,
            'message' => 'Transaction deleted successfully!'
        ]);
    }
}

resources/views/transaction/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-10">
                            <h4 class="w-75">Create Clients</h4>
                        </div>
                    </div>
                </div>
                <form method="post" action="{{route('transaction.store')}}">
                    {{csrf_field()}}
                <div class="card-body">
                    <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="firstName">Select Client</label>
                                    <select class="form-control" id="client_id" name="client_id">
                                        <option value="">-- Select Client --</option>
                                       @foreach($clients as $client)
                                           <option value="{{$client->id}}">{{$client->first_name}} {{$client->last_name}}</option>
                                       @endforeach
                                    </select>
                                    @if($errors->has('client_id'))
                                        <small class="text-danger">
                                            {{$errors->first('client_id')}}
                                        </small>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="lastName">Amount</label>
                                    <input type="number" name="amount" class="form-control" id="amount" placeholder="Enter Amount" value="{{old('last_name')}}">
                                    @if($errors->has('amount'))
                                        <small class="text-danger">
                                            {{$errors->first('amount')}}
                                        </small>
                                    @endif
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="email">Transaction Date</label>
                                    <input type="date" class="form-control" name="transaction_date" id="transaction_date" placeholder="Enter Transaction Date" value="{{old('email')}}">
                                    @if($errors->has('transaction_date'))
                                        <small class="text-danger">
                                            {{$errors->first('transaction_date')}}
                                        </small>
                                    @endif
                                </div>
                            </div>

                    </div>
                </div>
                <div class="card-footer text-right">
                    <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Save</button>
                    <button type="submit" class="btn btn-danger waves-effect waves-light m-r-10">Back</button>

                </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')

@endsection

resources/views/transaction/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-10">
                            <h4 class="w-75">Edit Transaction</h4>
                        </div>
                    </div>
                </div>
                <form method="post" action="{{route('transaction.update',$transaction)}}" >
                <div class="card-body">
                    <div class="row">
                            {{csrf_field()}}
                        {{method_field('PATCH')}}
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="firstName">Select Client</label>
                                <select class="form-control" id="client_id" name="client_id">
                                    <option value="">-- Select Client --</option>
                                    @foreach($clients as $client)
                                        <option value="{{$client->id}}" @if($client->id == $transaction->client_id) selected @endif>{{$client->first_name}} {{$client->last_name}}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('client_id'))
                                    <small class="text-danger">
                                        {{$errors->first('client_id')}}
                                    </small>
                                @endif
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="lastName">Amount</label>
                                <input type="number" name="amount" class="form-control" id="amount" placeholder="Enter Amount" value="{{$transaction->amount}}">
                                @if($errors->has('amount'))
                                    <small class="text-danger">
                                        {{$errors->first('amount')}}
                                    </small>
                                @endif
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="email">Transaction Date</label>
                                <input type="date" class="form-control" name="transaction_date" id="transaction_date" placeholder="Enter Transaction Date" value="{{\Carbon\Carbon::parse($transaction->transaction_date)->format('Y-m-d')}}" >
                                @if($errors->has('transaction_date'))
                                    <small class="text-danger">
                                        {{$errors->first('transaction_date')}}
                                    </small>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-right">
                    <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Save</button>
                    <button type="submit" class="btn btn-danger waves-effect waves-light m-r-10">Back</button>

                </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script>
    // $('#transaction_date').val('');
</script>
@endsection

resources/views/transaction/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">


        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-9">
                            <h4 class="w-75">Transactions</h4>
                        </div>
                        <div class="col-md-3 float-right">
                            <a href="{{route('transaction.create')}}" class="btn btn-primary">Add New Transaction</a>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <table class="table table-bordered" id="transaction-table">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Client Name</th>
                            <th>Amount</th>
                            <th>Transaction Date</th>
                            <th width="12%">Action</th>

                        </tr>
                        </thead>
                    </table>


                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')

    <script>
        $(function() {
            var table = $('#transaction-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{!! route('transaction.index') !!}',
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'client_name', name: 'client_name' },
                    { data: 'amount', name: 'amount',
                        "render": function (data, type, full, meta) {
                            return '£'+data;
                        },
                    },
                    { data: 'transaction_date', name: 'transaction_date'},
                    { data: 'action', name: 'action',orderable: false }
                ]
            });


        });

        function deleteTransaction(id) {

            swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this data!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        $.ajax({
                            url : "{{ url('transaction')}}" + '/' + id,
                            type : "POST",
                            data : {'_method' : 'DELETE',_token : '{!! csrf_token() !!}'},
                            success: function(response){
                                swal(response.message, {
                                    icon: "success",
                                });
                                var table = $('#transaction-table').DataTable();
                                table.ajax.reload();

                            },
                            error : function(){
                                swal({
                                    title: 'Opps...',
                                    text : response.message,
                                    type : 'error',
                                    timer : '1500'
                                })
                            }
                        })
                    } else {
                        swal("Your imaginary file is safe!");
                    }
                });
        }


    </script>
    @if(\Illuminate\Support\Facades\Session::has('success'))
        <script>
            swal("Good job!", "{{Session::get('success')}}", "success")
        </script>

    @endif
@endsection