routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


/* Route for Clients functionality */
Route::resource('client','ClientController')->except([
    'show'
]);

/* Route for Transaction functionality */
Route::resource('transaction','TransactionController')->except([
    'show'
]);

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = ['first_name','last_name','email','avatar'];
    
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use Illuminate\Http\Request;
use DataTables;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $clients = \App\Client::select('*');
            return DataTables::of($clients)
                ->editColumn('avatar', function ($query) {
                    return asset('storage/images') . '/' . $query->avatar;
                })
                ->addColumn('action', function ($query) {
                    $btn = '<a href="' . route('client.edit', $query->id) . '" class="btn dt-custom-button"><i class="fa fa-pencil fa-lg"></i> </a>
                            <a href="javascript:void(0)" onclick="deleteClient(' . $query->id . ')" class="btn dt-custom-button"><i class="fa fa-trash fa-lg"></i> </a>';
                    return $btn;
                })
                ->rawColumns(['action'])
                ->addIndexColumn()
                ->make(true);
        }
        return view('client.index');


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'required|email',
            'avatar' => 'required|image|mimes:jpeg,png,jpg,gif,svg|dimensions:min_width=100,min_height=100',
        ]);


        $client = new Client();
        $client->first_name = $request->first_name;
        $client->last_name = $request->last_name;
        if ($request->hasFile('avatar')) {
            $avatar = $request->file('avatar');
            $fileName = time() . '.' . $avatar->getClientOriginalExtension();
            Storage::disk('public')->put('images' . '/' . $fileName, File::get($avatar));
            $client->avatar = $fileName;
        }
        $client->email = $request->email;
        $client->save();


        return redirect(route('client.index'))->with('success', 'Client Added Successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Client $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        $client->avatar = asset('storage/images') . '/' . $client->avatar;
        return view('client.edit', ['client' => $client]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Client $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {

        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'required|email',
//            'avatar'=>'required|image|mimes:jpeg,png,jpg,gif,svg|dimensions:min_width=100,min_height=100',
        ]);

        //update record in database

        $client->first_name = $request->first_name;
        $client->last_name = $request->last_name;
        if ($request->hasFile('avatar')) {
            $avatar = $request->file('avatar');
            $fileName = time() . '.' . $avatar->getClientOriginalExtension();
            Storage::disk('public')->put('images' . '/' . $fileName, File::get($avatar));
            $client->avatar = $fileName;
        }
        $client->email = $request->email;
        $client->save();


        return redirect(route('client.index'))->with('success', 'Client Updated Successfully.');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Client $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {


        if ($client->avatar != 'default.png') {
            //Remove file from storage when client delete
            unlink(storage_path('app/public/images') . '/' . $client->avatar);
        }

        //delete record from database
        $client->delete();

        return response()->json([
            'success' => true,
            'message' => 'Client deleted successfully!'
        ]);
    }
}

resources/views/client/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-10">
                            <h4 class="w-75">Create Clients</h4>
                        </div>
                    </div>
                </div>
                <form method="post" action="{{route('client.store')}}" enctype="multipart/form-data">
                    {{csrf_field()}}
                <div class="card-body">
                    <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="firstName">First Name</label>
                                    <input type="text" name="first_name" class="form-control" id="first_name" placeholder="Enter your First Name" value="{{old('first_name')}}">
                                    @if($errors->has('first_name'))
                                        <small class="text-danger">
                                            {{$errors->first('first_name')}}
                                        </small>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="lastName">Last Name</label>
                                    <input type="text" name="last_name" class="form-control" id="last_name" placeholder="Enter your Last Name" value="{{old('last_name')}}">
                                    @if($errors->has('last_name'))
                                        <small class="text-danger">
                                            {{$errors->first('last_name')}}
                                        </small>
                                    @endif
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="email">Email address</label>
                                    <input type="email" class="form-control" name="email" id="email" placeholder="Enter your Email" value="{{old('email')}}">
                                    @if($errors->has('email'))
                                        <small class="text-danger">
                                            {{$errors->first('email')}}
                                        </small>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="avatar">Select Avatar</label>
                                    <input type="file" class="form-control-file" id="avatar" name="avatar">
                                    @if($errors->has('avatar'))
                                        <small class="text-danger">
                                            {{$errors->first('avatar')}}
                                        </small>
                                    @endif
                                </div>
                            </div>


                    </div>
                </div>
                <div class="card-footer text-right">
                    <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Save</button>
                    <button type="submit" class="btn btn-danger waves-effect waves-light m-r-10">Back</button>

                </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')

@endsection

resources/views/client/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-10">
                            <h4 class="w-75">Edit Clients</h4>
                        </div>
                    </div>
                </div>
                <form method="post" action="{{route('client.update',$client)}}" enctype="multipart/form-data">
                <div class="card-body">
                    <div class="row">
                            {{csrf_field()}}
                        {{method_field('PATCH')}}
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="firstName">First Name</label>
                                    <input type="text" name="first_name" class="form-control" id="first_name" placeholder="Enter your First Name" value="{{$client->first_name}}">
                                    @if($errors->has('first_name'))
                                        <small class="text-danger">
                                            {{$errors->first('first_name')}}
                                        </small>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="lastName">Last Name</label>
                                    <input type="text" name="last_name" class="form-control" id="last_name" placeholder="Enter your Last Name" value="{{$client->last_name}}">
                                    @if($errors->has('last_name'))
                                        <small class="text-danger">
                                            {{$errors->first('last_name')}}
                                        </small>
                                    @endif
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="email">Email address</label>
                                    <input type="email" class="form-control" name="email" id="email" placeholder="Enter your Email" value="{{$client->email}}">
                                    @if($errors->has('email'))
                                        <small class="text-danger">
                                            {{$errors->first('email')}}
                                        </small>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-12">

                                <div class="col-md-2">
                                    <img src="{{$client->avatar}}" width="100" height="100">
                                </div>
                                <div class="col-md-8">
                                    <div class="form-group">
                                        <label for="avatar">Select Avatar</label>
                                        <input type="file" class="form-control-file" id="avatar" name="avatar">
                                        @if($errors->has('avatar'))
                                            <small class="text-danger">
                                                {{$errors->first('avatar')}}
                                            </small>
                                        @endif
                                    </div>
                                </div>
                            </div>


                    </div>
                </div>
                <div class="card-footer text-right">
                    <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Save</button>
                    <button type="submit" class="btn btn-danger waves-effect waves-light m-r-10">Back</button>

                </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')

@endsection

resources/views/client/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">


        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-10">
                            <h4 class="w-75">Clients</h4>
                        </div>
                        <div class="col-md-2 float-right">
                            <a href="{{route('client.create')}}" class="btn btn-primary">Add New Client</a>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <table class="table table-bordered" id="client-table">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Avtar</th>
                            <th>Email</th>
                            <th width="12%">Action</th>

                        </tr>
                        </thead>
                    </table>


                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')

    <script>
        $(function() {
            var table = $('#client-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{!! route('client.index') !!}',
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'first_name', name: 'first_name' },
                    { data: 'last_name', name: 'last_name' },
                    { data: 'avatar', name: 'avatar',orderable: false,
                        "render": function (data, type, full, meta) {
                            return '<img src="'+ data +'" height="25"/>';
                        },},
                    { data: 'email', name: 'email' },
                    { data: 'action', name: 'action',orderable: false }
                ]
            });


        });

        function deleteClient(id) {

            swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this data!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        $.ajax({
                            url : "{{ url('client')}}" + '/' + id,
                            type : "POST",
                            data : {'_method' : 'DELETE',_token : '{!! csrf_token() !!}'},
                            success: function(response){
                                swal(response.message, {
                                    icon: "success",
                                });
                                var table = $('#client-table').DataTable();
                                table.ajax.reload();

                            },
                            error : function(){
                                swal({
                                    title: 'Opps...',
                                    text : response.message,
                                    type : 'error',
                                    timer : '1500'
                                })
                            }
                        })
                    } else {
                        swal("Your imaginary file is safe!");
                    }
                });
        }


    </script>
    @if(\Illuminate\Support\Facades\Session::has('success'))
        <script>
            swal("Good job!", "{{Session::get('success')}}", "success")
        </script>

    @endif
@endsection